# Number of days of inactivity before an Issue or Pull Request becomes stale
daysUntilStale: 182

# Label to use when marking as stale
staleLabel: stale

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs.

# Limit to only `issues` or `pulls`
only: issues
